### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto-busca-minas#2]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by lquintanac** [comment]
Hola buenas, si tenéis subido el fichero del menú de programa tenéis que cerrar la issue.

**Comment by lquintanac** [comment]
Hola buenas, he visto que tenéis ya subido el archivo del menú provisional. Recordar cerrar esta issue.

**Comment by oscarperpinan** [comment]
El código del menú debe estar contenido en un fichero con extensión .c

El menú que habéis implementado es extremadamente simple. El proyecto deberá ganar en complejidad si queréis obtener una buena evaluación.

**Comment by oscarperpinan** [comment]
Para cerrar una issue debéis atender previamente a mis indicaciones. Insisto: el código debe estar contenido en un fichero con extensión .c
